from pymarrmot.models.flux.baseflow.baseflow_1 import baseflow_1
from pymarrmot.models.flux.baseflow.baseflow_2 import baseflow_2
from pymarrmot.models.flux.baseflow.baseflow_3 import baseflow_3
from pymarrmot.models.flux.baseflow.baseflow_4 import baseflow_4
from pymarrmot.models.flux.baseflow.baseflow_5 import baseflow_5
from pymarrmot.models.flux.baseflow.baseflow_6 import baseflow_6
from pymarrmot.models.flux.baseflow.baseflow_7 import baseflow_7
from pymarrmot.models.flux.baseflow.baseflow_8 import baseflow_8
from pymarrmot.models.flux.baseflow.baseflow_9 import baseflow_9