from pymarrmot.models.flux.interflow.interflow_1 import interflow_1
from pymarrmot.models.flux.interflow.interflow_2 import interflow_2
from pymarrmot.models.flux.interflow.interflow_3 import interflow_3
from pymarrmot.models.flux.interflow.interflow_4 import interflow_4
from pymarrmot.models.flux.interflow.interflow_5 import interflow_5
from pymarrmot.models.flux.interflow.interflow_6 import interflow_6
from pymarrmot.models.flux.interflow.interflow_7 import interflow_7
from pymarrmot.models.flux.interflow.interflow_8 import interflow_8
from pymarrmot.models.flux.interflow.interflow_9 import interflow_9
from pymarrmot.models.flux.interflow.interflow_10 import interflow_10
from pymarrmot.models.flux.interflow.interflow_11 import interflow_11
from pymarrmot.models.flux.interflow.interflow_12 import interflow_12