from pymarrmot.models.flux.evaporation.evap_1 import evap_1
from pymarrmot.models.flux.evaporation.evap_2 import evap_2
from pymarrmot.models.flux.evaporation.evap_3 import evap_3
from pymarrmot.models.flux.evaporation.evap_4 import evap_4
from pymarrmot.models.flux.evaporation.evap_5 import evap_5
from pymarrmot.models.flux.evaporation.evap_6 import evap_6
from pymarrmot.models.flux.evaporation.evap_7 import evap_7
from pymarrmot.models.flux.evaporation.evap_8 import evap_8
from pymarrmot.models.flux.evaporation.evap_9 import evap_9
from pymarrmot.models.flux.evaporation.evap_10 import evap_10
from pymarrmot.models.flux.evaporation.evap_11 import evap_11
from pymarrmot.models.flux.evaporation.evap_12 import evap_12
from pymarrmot.models.flux.evaporation.evap_13 import evap_13
from pymarrmot.models.flux.evaporation.evap_14 import evap_14
from pymarrmot.models.flux.evaporation.evap_15 import evap_15
from pymarrmot.models.flux.evaporation.evap_16 import evap_16
from pymarrmot.models.flux.evaporation.evap_17 import evap_17
from pymarrmot.models.flux.evaporation.evap_18 import evap_18
from pymarrmot.models.flux.evaporation.evap_19 import evap_19
from pymarrmot.models.flux.evaporation.evap_20 import evap_20
from pymarrmot.models.flux.evaporation.evap_21 import evap_21
from pymarrmot.models.flux.evaporation.evap_22 import evap_22
from pymarrmot.models.flux.evaporation.evap_23 import evap_23